import { assetUrls } from "@/game/assets";
import type { ArenaDefinition } from "@/game/runtime";
import { vec3 } from "@/game/math";

export const arenaDefinition: ArenaDefinition = {
  bounds: {
    width: 34,
    depth: 28,
  },
  groundModelUrl: assetUrls.environment.ground,
  playerStart: vec3(0, 0, 8),
  recruitStaging: [vec3(-4, 0, 12), vec3(0, 0, 12), vec3(4, 0, 12)],
  companionSlots: [vec3(-2.5, 0, 9.5), vec3(0, 0, 10), vec3(2.5, 0, 9.5)],
  enemySpawnPoints: [
    vec3(-7, 0, -8),
    vec3(0, 0, -10),
    vec3(7, 0, -8),
    vec3(-9, 0, -4),
    vec3(9, 0, -4),
    vec3(0, 0, -14),
  ],
  retreatPoint: vec3(0, 0, 12.5),
  defendPoint: vec3(0, 0, 2),
  obstacles: [
    {
      id: "center_wall",
      kind: "wall",
      position: vec3(0, 0, -1),
      rotationY: 0,
      size: { x: 7, y: 2.6, z: 1.6 },
      modelUrl: assetUrls.environment.wall,
      blocksMovement: true,
    },
    {
      id: "left_cover_crate",
      kind: "crate",
      position: vec3(-8, 0, 2.5),
      rotationY: 0,
      size: { x: 2.1, y: 2.1, z: 2.1 },
      modelUrl: assetUrls.environment.crate,
      blocksMovement: true,
    },
    {
      id: "right_cover_crate",
      kind: "crate",
      position: vec3(8, 0, 2.5),
      rotationY: 0,
      size: { x: 2.1, y: 2.1, z: 2.1 },
      modelUrl: assetUrls.environment.crate,
      blocksMovement: true,
    },
    {
      id: "north_fence_left",
      kind: "fence",
      position: vec3(-10.5, 0, -11.5),
      rotationY: 0,
      size: { x: 5.4, y: 1.4, z: 0.8 },
      modelUrl: assetUrls.environment.fenceLong,
      blocksMovement: true,
    },
    {
      id: "north_fence_right",
      kind: "fence",
      position: vec3(10.5, 0, -11.5),
      rotationY: 0,
      size: { x: 5.4, y: 1.4, z: 0.8 },
      modelUrl: assetUrls.environment.fenceLong,
      blocksMovement: true,
    },
    {
      id: "south_archway",
      kind: "archway",
      position: vec3(0, 0, 13.2),
      rotationY: Math.PI,
      size: { x: 5.4, y: 4.5, z: 1.2 },
      modelUrl: assetUrls.environment.archway,
      blocksMovement: false,
    },
    {
      id: "east_timber",
      kind: "timber",
      position: vec3(12.5, 0, -1.5),
      rotationY: Math.PI / 2,
      size: { x: 1.1, y: 3, z: 7.5 },
      modelUrl: assetUrls.environment.timberWall,
      blocksMovement: true,
    },
    {
      id: "west_timber",
      kind: "timber",
      position: vec3(-12.5, 0, -1.5),
      rotationY: Math.PI / 2,
      size: { x: 1.1, y: 3, z: 7.5 },
      modelUrl: assetUrls.environment.timberWall,
      blocksMovement: true,
    },
    {
      id: "east_detail_fence",
      kind: "fence",
      position: vec3(14.2, 0, 7.8),
      rotationY: Math.PI / 2,
      size: { x: 3.2, y: 1.6, z: 0.8 },
      modelUrl: assetUrls.environment.metalFence,
      blocksMovement: false,
    },
    {
      id: "west_detail_fence",
      kind: "fence",
      position: vec3(-14.2, 0, 7.8),
      rotationY: Math.PI / 2,
      size: { x: 3.2, y: 1.6, z: 0.8 },
      modelUrl: assetUrls.environment.metalFence,
      blocksMovement: false,
    },
  ],
};
