const resolveAssetUrl = (relativePath: string) => new URL(relativePath, import.meta.url).href;

export const assetUrls = {
  characters: {
    leader: resolveAssetUrl("../../../assets/game/characters/leader/char_human_swordshield_01.fbx"),
    companionArcher: resolveAssetUrl("../../../assets/game/characters/companions/char_human_archer_01.fbx"),
    enemyAxe: resolveAssetUrl("../../../assets/game/characters/enemies/char_human_axe_01.fbx"),
  },
  environment: {
    ground: resolveAssetUrl("../../../assets/game/environment/arena_outdoor/ground/env_ground_arena_brick_01.gltf"),
    crate: resolveAssetUrl("../../../assets/game/environment/arena_outdoor/obstacles/env_obstacle_crate_01.gltf"),
    fenceShort: resolveAssetUrl("../../../assets/game/environment/arena_outdoor/obstacles/env_obstacle_fence_wood_01.gltf"),
    fenceLong: resolveAssetUrl("../../../assets/game/environment/arena_outdoor/obstacles/env_obstacle_fence_wood_02.gltf"),
    wall: resolveAssetUrl("../../../assets/game/environment/arena_outdoor/obstacles/env_obstacle_wall_stone_01.gltf"),
    archway: resolveAssetUrl("../../../assets/game/environment/arena_outdoor/props/env_prop_archway_01.gltf"),
    metalFence: resolveAssetUrl("../../../assets/game/environment/arena_outdoor/props/env_prop_fence_metal_01.gltf"),
    timberWall: resolveAssetUrl("../../../assets/game/environment/arena_outdoor/props/env_prop_wall_timber_01.gltf"),
  },
  weapons: {
    saber: resolveAssetUrl("../../../assets/game/weapons/melee/weapon_sword_saber_01.gltf"),
    halberd: resolveAssetUrl("../../../assets/game/weapons/melee/weapon_halberd_01.gltf"),
    bow: resolveAssetUrl("../../../assets/game/weapons/ranged/weapon_bow_long_01.gltf"),
    bowString: resolveAssetUrl("../../../assets/game/weapons/ranged/weapon_bow_long_string_01.gltf"),
    staff: resolveAssetUrl("../../../assets/game/weapons/ranged/weapon_staff_01.gltf"),
    staffAlt: resolveAssetUrl("../../../assets/game/weapons/ranged/weapon_staff_02.gltf"),
    maul: resolveAssetUrl("../../../assets/game/weapons/melee/weapon_hammer_maul_01.gltf"),
    axe: resolveAssetUrl("../../../assets/game/weapons/melee/weapon_axe_battle_01.gltf"),
  },
  ui: {
    barBack: resolveAssetUrl("../../../assets/game/ui/frames/ui_bar_back_01.png"),
    barFill: resolveAssetUrl("../../../assets/game/ui/frames/ui_bar_fill_01.png"),
    button: resolveAssetUrl("../../../assets/game/ui/frames/ui_frame_button_rect_01.png"),
    orderButton: resolveAssetUrl("../../../assets/game/ui/frames/ui_frame_order_button_01.png"),
    slot: resolveAssetUrl("../../../assets/game/ui/frames/ui_frame_slot_01.png"),
    panel: resolveAssetUrl("../../../assets/game/ui/panels/ui_panel_basic_01.png"),
    panelFill: resolveAssetUrl("../../../assets/game/ui/panels/ui_panel_fill_01.png"),
    targetEnemy: resolveAssetUrl("../../../assets/game/ui/markers/ui_marker_target_enemy_01.png"),
    targetAlly: resolveAssetUrl("../../../assets/game/ui/markers/ui_marker_target_ally_01.png"),
    orderMove: resolveAssetUrl("../../../assets/game/ui/markers/ui_marker_order_move_01.png"),
    rewardSword: resolveAssetUrl("../../../assets/game/ui/icons/ui_icon_reward_weapon_sword_01.png"),
    rewardAxe: resolveAssetUrl("../../../assets/game/ui/icons/ui_icon_reward_weapon_axe_01.png"),
    rewardStaff: resolveAssetUrl("../../../assets/game/ui/icons/ui_icon_reward_staff_01.png"),
    rewardShield: resolveAssetUrl("../../../assets/game/ui/icons/ui_icon_reward_shield_01.png"),
    star: resolveAssetUrl("../../../assets/game/ui/icons/ui_icon_star_01.png"),
  },
  audio: {
    hitBlade: resolveAssetUrl("../../../assets/game/audio/impacts/audio_hit_blade_01.ogg"),
    hitBody: resolveAssetUrl("../../../assets/game/audio/impacts/audio_hit_body_01.ogg"),
    hitRanged: resolveAssetUrl("../../../assets/game/audio/impacts/audio_hit_ranged_01.ogg"),
    spellImpact: resolveAssetUrl("../../../assets/game/audio/spells/audio_spell_arcane_impact_01.ogg"),
    uiConfirm: resolveAssetUrl("../../../assets/game/audio/ui/audio_ui_confirm_01.ogg"),
    uiCancel: resolveAssetUrl("../../../assets/game/audio/ui/audio_ui_cancel_01.ogg"),
    uiLevelUp: resolveAssetUrl("../../../assets/game/audio/ui/audio_ui_levelup_01.ogg"),
  },
  vfx: {
    spellCast: resolveAssetUrl("../../../assets/game/vfx/spells/vfx_spell_cast_01.png"),
    spellProjectile: resolveAssetUrl("../../../assets/game/vfx/spells/vfx_spell_projectile_01.png"),
    spellImpactArcane: resolveAssetUrl("../../../assets/game/vfx/spells/vfx_spell_impact_arcane_01.png"),
    spellImpactSupport: resolveAssetUrl("../../../assets/game/vfx/spells/vfx_spell_impact_support_01.png"),
    hitSlash: resolveAssetUrl("../../../assets/game/vfx/hits/vfx_hit_slash_01.png"),
    hitArcane: resolveAssetUrl("../../../assets/game/vfx/hits/vfx_hit_arcane_01.png"),
    downed: resolveAssetUrl("../../../assets/game/vfx/status/vfx_status_downed_01.png"),
    revive: resolveAssetUrl("../../../assets/game/vfx/status/vfx_status_revive_01.png"),
    buff: resolveAssetUrl("../../../assets/game/vfx/status/vfx_status_buff_01.png"),
    warning: resolveAssetUrl("../../../assets/game/vfx/status/vfx_status_warning_01.png"),
  },
} as const;
