const resolveAssetUrl = (publicPath: string) => publicPath;

export const assetUrls = {
  characters: {
    leader: resolveAssetUrl("/game/characters/leader/char_human_swordshield_01.fbx"),
    companionArcher: resolveAssetUrl("/game/characters/companions/char_human_archer_01.fbx"),
    enemyAxe: resolveAssetUrl("/game/characters/enemies/char_human_axe_01.fbx"),
  },
  characterAnimations: {
    leader: {
      idle: resolveAssetUrl("/game/characters/leader/anim_leader_swordshield_idle_01.fbx"),
      run: resolveAssetUrl("/game/characters/leader/anim_leader_swordshield_run_01.fbx"),
      attack: resolveAssetUrl("/game/characters/leader/anim_leader_swordshield_attack_01.fbx"),
      cast: resolveAssetUrl("/game/characters/leader/anim_leader_swordshield_cast_01.fbx"),
      hit: resolveAssetUrl("/game/characters/leader/anim_leader_swordshield_hit_01.fbx"),
      death: resolveAssetUrl("/game/characters/leader/anim_leader_swordshield_death_01.fbx"),
      block: resolveAssetUrl("/game/characters/leader/anim_leader_swordshield_block_01.fbx"),
    },
    archer: {
      idle: resolveAssetUrl("/game/characters/companions/anim_archer_idle_01.fbx"),
      run: resolveAssetUrl("/game/characters/companions/anim_archer_run_01.fbx"),
      attack: resolveAssetUrl("/game/characters/companions/anim_archer_attack_01.fbx"),
      draw: resolveAssetUrl("/game/characters/companions/anim_archer_draw_01.fbx"),
      release: resolveAssetUrl("/game/characters/companions/anim_archer_release_01.fbx"),
      hit: resolveAssetUrl("/game/characters/companions/anim_archer_hit_01.fbx"),
      death: resolveAssetUrl("/game/characters/companions/anim_archer_death_01.fbx"),
    },
    axe: {
      idle: resolveAssetUrl("/game/characters/enemies/anim_axe_idle_01.fbx"),
      run: resolveAssetUrl("/game/characters/enemies/anim_axe_run_01.fbx"),
      attack: resolveAssetUrl("/game/characters/enemies/anim_axe_attack_01.fbx"),
      attackAlt: resolveAssetUrl("/game/characters/enemies/anim_axe_attack_02.fbx"),
      guard: resolveAssetUrl("/game/characters/enemies/anim_axe_guard_01.fbx"),
      hit: resolveAssetUrl("/game/characters/enemies/anim_axe_hit_01.fbx"),
    },
  },
  environment: {
    ground: resolveAssetUrl("/game/environment/arena_outdoor/ground/env_ground_arena_brick_01.gltf"),
    crate: resolveAssetUrl("/game/environment/arena_outdoor/obstacles/env_obstacle_crate_01.gltf"),
    fenceShort: resolveAssetUrl("/game/environment/arena_outdoor/obstacles/env_obstacle_fence_wood_01.gltf"),
    fenceLong: resolveAssetUrl("/game/environment/arena_outdoor/obstacles/env_obstacle_fence_wood_02.gltf"),
    wall: resolveAssetUrl("/game/environment/arena_outdoor/obstacles/env_obstacle_wall_stone_01.gltf"),
    archway: resolveAssetUrl("/game/environment/arena_outdoor/props/env_prop_archway_01.gltf"),
    metalFence: resolveAssetUrl("/game/environment/arena_outdoor/props/env_prop_fence_metal_01.gltf"),
    timberWall: resolveAssetUrl("/game/environment/arena_outdoor/props/env_prop_wall_timber_01.gltf"),
  },
  weapons: {
    saber: resolveAssetUrl("/game/weapons/melee/weapon_sword_saber_01.gltf"),
    halberd: resolveAssetUrl("/game/weapons/melee/weapon_halberd_01.gltf"),
    bow: resolveAssetUrl("/game/weapons/ranged/weapon_bow_long_01.gltf"),
    bowString: resolveAssetUrl("/game/weapons/ranged/weapon_bow_long_string_01.gltf"),
    staff: resolveAssetUrl("/game/weapons/ranged/weapon_staff_01.gltf"),
    staffAlt: resolveAssetUrl("/game/weapons/ranged/weapon_staff_02.gltf"),
    maul: resolveAssetUrl("/game/weapons/melee/weapon_hammer_maul_01.gltf"),
    axe: resolveAssetUrl("/game/weapons/melee/weapon_axe_battle_01.gltf"),
  },
  ui: {
    barBack: resolveAssetUrl("/game/ui/frames/ui_bar_back_01.png"),
    barFill: resolveAssetUrl("/game/ui/frames/ui_bar_fill_01.png"),
    button: resolveAssetUrl("/game/ui/frames/ui_frame_button_rect_01.png"),
    orderButton: resolveAssetUrl("/game/ui/frames/ui_frame_order_button_01.png"),
    slot: resolveAssetUrl("/game/ui/frames/ui_frame_slot_01.png"),
    panel: resolveAssetUrl("/game/ui/panels/ui_panel_basic_01.png"),
    panelFill: resolveAssetUrl("/game/ui/panels/ui_panel_fill_01.png"),
    targetEnemy: resolveAssetUrl("/game/ui/markers/ui_marker_target_enemy_01.png"),
    targetAlly: resolveAssetUrl("/game/ui/markers/ui_marker_target_ally_01.png"),
    orderMove: resolveAssetUrl("/game/ui/markers/ui_marker_order_move_01.png"),
    rewardSword: resolveAssetUrl("/game/ui/icons/ui_icon_reward_weapon_sword_01.png"),
    rewardAxe: resolveAssetUrl("/game/ui/icons/ui_icon_reward_weapon_axe_01.png"),
    rewardStaff: resolveAssetUrl("/game/ui/icons/ui_icon_reward_staff_01.png"),
    rewardShield: resolveAssetUrl("/game/ui/icons/ui_icon_reward_shield_01.png"),
    star: resolveAssetUrl("/game/ui/icons/ui_icon_star_01.png"),
  },
  audio: {
    hitBlade: resolveAssetUrl("/game/audio/impacts/audio_hit_blade_01.ogg"),
    hitBody: resolveAssetUrl("/game/audio/impacts/audio_hit_body_01.ogg"),
    hitRanged: resolveAssetUrl("/game/audio/impacts/audio_hit_ranged_01.ogg"),
    spellImpact: resolveAssetUrl("/game/audio/spells/audio_spell_arcane_impact_01.ogg"),
    uiConfirm: resolveAssetUrl("/game/audio/ui/audio_ui_confirm_01.ogg"),
    uiCancel: resolveAssetUrl("/game/audio/ui/audio_ui_cancel_01.ogg"),
    uiLevelUp: resolveAssetUrl("/game/audio/ui/audio_ui_levelup_01.ogg"),
  },
  vfx: {
    spellCast: resolveAssetUrl("/game/vfx/spells/vfx_spell_cast_01.png"),
    spellProjectile: resolveAssetUrl("/game/vfx/spells/vfx_spell_projectile_01.png"),
    spellImpactArcane: resolveAssetUrl("/game/vfx/spells/vfx_spell_impact_arcane_01.png"),
    spellImpactSupport: resolveAssetUrl("/game/vfx/spells/vfx_spell_impact_support_01.png"),
    hitSlash: resolveAssetUrl("/game/vfx/hits/vfx_hit_slash_01.png"),
    hitArcane: resolveAssetUrl("/game/vfx/hits/vfx_hit_arcane_01.png"),
    downed: resolveAssetUrl("/game/vfx/status/vfx_status_downed_01.png"),
    revive: resolveAssetUrl("/game/vfx/status/vfx_status_revive_01.png"),
    buff: resolveAssetUrl("/game/vfx/status/vfx_status_buff_01.png"),
    warning: resolveAssetUrl("/game/vfx/status/vfx_status_warning_01.png"),
  },
} as const;
