import { assetUrls } from "@/game/assets";
import type {
  BehaviorProfileDefinition,
  FactionDefinition,
  OrderDefinition,
  PrototypeCatalog,
  RewardDefinition,
  SpellDefinition,
  SpellLoadoutDefinition,
  StatusDefinition,
  UnitDefinition,
  WeaponDefinition,
} from "@/game/defs";

const byId = <T extends { id: string }>(values: T[]) =>
  Object.fromEntries(values.map((value) => [value.id, value])) as Record<T["id"], T>;

const factions: FactionDefinition[] = [
  {
    id: "leader_party",
    name: "Command",
    color: "#58a2ff",
    isFriendlyTo: ["leader_party"],
  },
  {
    id: "enemy",
    name: "Raiders",
    color: "#ff6c5f",
    isFriendlyTo: ["enemy"],
  },
];

const weapons: WeaponDefinition[] = [
  {
    id: "captain_saber",
    name: "Officer Saber",
    kind: "melee",
    description: "Fast, dependable saber slashes for the leader.",
    range: 2.6,
    cooldownMs: 900,
    baseDamage: 16,
    preferredDistance: 2.1,
    asset: {
      modelUrl: assetUrls.weapons.saber,
      sfxUrl: assetUrls.audio.hitBlade,
      vfxUrl: assetUrls.vfx.hitSlash,
    },
  },
  {
    id: "vanguard_halberd",
    name: "Halberd",
    kind: "melee",
    description: "Wide melee pressure with extra reach.",
    range: 3.1,
    cooldownMs: 1150,
    baseDamage: 18,
    preferredDistance: 2.7,
    asset: {
      modelUrl: assetUrls.weapons.halberd,
      sfxUrl: assetUrls.audio.hitBlade,
      vfxUrl: assetUrls.vfx.hitSlash,
    },
  },
  {
    id: "ranger_longbow",
    name: "Longbow",
    kind: "ranged",
    description: "Steady ranged basic attacks for reliable filler damage.",
    range: 15,
    cooldownMs: 1300,
    baseDamage: 14,
    projectileSpeed: 18,
    preferredDistance: 10,
    asset: {
      modelUrl: assetUrls.weapons.bow,
      sfxUrl: assetUrls.audio.hitRanged,
      vfxUrl: assetUrls.vfx.spellProjectile,
    },
  },
  {
    id: "mender_staff",
    name: "Field Staff",
    kind: "focus",
    description: "Arcane focus for support basics and healing casts.",
    range: 11,
    cooldownMs: 1400,
    baseDamage: 10,
    projectileSpeed: 15,
    preferredDistance: 8.5,
    asset: {
      modelUrl: assetUrls.weapons.staff,
      sfxUrl: assetUrls.audio.spellImpact,
      vfxUrl: assetUrls.vfx.hitArcane,
    },
  },
  {
    id: "raider_axe",
    name: "Raider Axe",
    kind: "melee",
    description: "Heavy melee chase tool for enemy raiders.",
    range: 2.4,
    cooldownMs: 1050,
    baseDamage: 15,
    preferredDistance: 2.1,
    asset: {
      modelUrl: assetUrls.weapons.axe,
      sfxUrl: assetUrls.audio.hitBlade,
      vfxUrl: assetUrls.vfx.hitSlash,
    },
  },
  {
    id: "hexcaster_staff",
    name: "Hex Staff",
    kind: "focus",
    description: "Caster staff for ranged spell harassment.",
    range: 13,
    cooldownMs: 1500,
    baseDamage: 11,
    projectileSpeed: 16,
    preferredDistance: 10.5,
    asset: {
      modelUrl: assetUrls.weapons.staffAlt,
      sfxUrl: assetUrls.audio.spellImpact,
      vfxUrl: assetUrls.vfx.hitArcane,
    },
  },
  {
    id: "bulwark_maul",
    name: "Disruptor Maul",
    kind: "melee",
    description: "Slow but disruptive tank weapon.",
    range: 2.8,
    cooldownMs: 1450,
    baseDamage: 20,
    preferredDistance: 2.3,
    asset: {
      modelUrl: assetUrls.weapons.maul,
      sfxUrl: assetUrls.audio.hitBody,
      vfxUrl: assetUrls.vfx.warning,
    },
  },
];

const statuses: StatusDefinition[] = [
  {
    id: "shielded",
    name: "Shielded",
    description: "Absorbs incoming damage before health is lost.",
    effectType: "shield",
    maxStacks: 1,
    defaultDurationMs: 4500,
    asset: { vfxUrl: assetUrls.vfx.buff },
  },
  {
    id: "slowed",
    name: "Slowed",
    description: "Reduces move speed while active.",
    effectType: "slow",
    maxStacks: 1,
    defaultDurationMs: 3200,
    asset: { vfxUrl: assetUrls.vfx.warning },
  },
  {
    id: "marked",
    name: "Marked",
    description: "Takes bonus focus damage from allied units.",
    effectType: "mark",
    maxStacks: 1,
    defaultDurationMs: 5000,
    asset: { vfxUrl: assetUrls.vfx.warning },
  },
  {
    id: "taunted",
    name: "Taunted",
    description: "Prefers the source as its current target.",
    effectType: "taunt",
    maxStacks: 1,
    defaultDurationMs: 2600,
    asset: { vfxUrl: assetUrls.vfx.warning },
  },
  {
    id: "battle_focus",
    name: "Battle Focus",
    description: "Short offensive buff for coordinated pushes.",
    effectType: "buff",
    maxStacks: 1,
    defaultDurationMs: 3500,
    asset: { vfxUrl: assetUrls.vfx.buff },
  },
  {
    id: "downed",
    name: "Downed",
    description: "Cannot act and must be revived before the bleed-out timer ends.",
    effectType: "buff",
    maxStacks: 1,
    defaultDurationMs: 18000,
    asset: { vfxUrl: assetUrls.vfx.downed },
  },
  {
    id: "reviving",
    name: "Reviving",
    description: "Temporary channel used when a unit is being revived.",
    effectType: "buff",
    maxStacks: 1,
    defaultDurationMs: 1500,
    asset: { vfxUrl: assetUrls.vfx.revive },
  },
];

const spells: SpellDefinition[] = [
  {
    id: "arcane_lance",
    name: "Arcane Lance",
    description: "Reliable ranged strike for the captain or support units.",
    cooldownMs: 4200,
    resourceCost: 14,
    castTimeMs: 300,
    range: 15,
    targetingMode: "enemy",
    areaShape: "single",
    projectileSpeed: 18,
    effects: [{ type: "damage", power: 30 }],
    aiTags: ["damage", "ranged", "opener"],
    asset: {
      vfxUrl: assetUrls.vfx.spellProjectile,
      sfxUrl: assetUrls.audio.spellImpact,
    },
  },
  {
    id: "commanders_mark",
    name: "Commander's Mark",
    description: "Marks a priority enemy and adds a burst of damage.",
    cooldownMs: 6000,
    resourceCost: 20,
    castTimeMs: 250,
    range: 16,
    targetingMode: "enemy",
    areaShape: "single",
    projectileSpeed: 16,
    effects: [
      { type: "damage", power: 18 },
      { type: "mark", power: 10, durationMs: 5000, statusId: "marked" },
    ],
    aiTags: ["damage", "mark", "focus"],
    asset: {
      vfxUrl: assetUrls.vfx.spellImpactArcane,
      sfxUrl: assetUrls.audio.spellImpact,
    },
  },
  {
    id: "bulwark_pulse",
    name: "Bulwark Pulse",
    description: "Applies a short shield and battle focus to allies in range.",
    cooldownMs: 8500,
    resourceCost: 18,
    castTimeMs: 400,
    range: 0,
    targetingMode: "self",
    areaShape: "circle",
    areaRadius: 5.5,
    effects: [
      { type: "shield", power: 32, durationMs: 4500, statusId: "shielded" },
      { type: "buff", power: 4, durationMs: 3500, statusId: "battle_focus" },
    ],
    aiTags: ["shield", "support"],
    asset: {
      vfxUrl: assetUrls.vfx.spellImpactSupport,
      sfxUrl: assetUrls.audio.uiConfirm,
    },
  },
  {
    id: "field_mend",
    name: "Field Mend",
    description: "Single-target heal used by the leader or the mender.",
    cooldownMs: 6500,
    resourceCost: 16,
    castTimeMs: 450,
    range: 12,
    targetingMode: "ally",
    areaShape: "single",
    effects: [{ type: "heal", power: 34 }],
    aiTags: ["heal", "support"],
    asset: {
      vfxUrl: assetUrls.vfx.spellImpactSupport,
      sfxUrl: assetUrls.audio.uiConfirm,
    },
  },
  {
    id: "steam_snare",
    name: "Steam Snare",
    description: "Ground-targeted slow field for zone control.",
    cooldownMs: 9000,
    resourceCost: 22,
    castTimeMs: 500,
    range: 14,
    targetingMode: "ground",
    areaShape: "circle",
    areaRadius: 3.8,
    effects: [
      { type: "damage", power: 14, radius: 3.8 },
      { type: "slow", power: 0.35, durationMs: 3200, radius: 3.8, statusId: "slowed" },
    ],
    aiTags: ["control", "slow"],
    asset: {
      vfxUrl: assetUrls.vfx.spellCast,
      sfxUrl: assetUrls.audio.spellImpact,
    },
  },
  {
    id: "volley_burst",
    name: "Volley Burst",
    description: "Ranger burst shot against the current focus target.",
    cooldownMs: 5800,
    resourceCost: 12,
    castTimeMs: 250,
    range: 16,
    targetingMode: "enemy",
    areaShape: "single",
    projectileSpeed: 20,
    effects: [{ type: "damage", power: 24 }],
    aiTags: ["damage", "opener"],
    asset: {
      vfxUrl: assetUrls.vfx.spellProjectile,
      sfxUrl: assetUrls.audio.hitRanged,
    },
  },
  {
    id: "guardian_shout",
    name: "Guardian Shout",
    description: "Frontliner taunt with a short defensive pulse.",
    cooldownMs: 8200,
    resourceCost: 16,
    castTimeMs: 350,
    range: 6,
    targetingMode: "self",
    areaShape: "circle",
    areaRadius: 4.6,
    effects: [
      { type: "taunt", power: 1, durationMs: 2600, radius: 4.6, statusId: "taunted" },
      { type: "shield", power: 22, durationMs: 3000, statusId: "shielded" },
    ],
    aiTags: ["taunt", "support", "frontline"],
    asset: {
      vfxUrl: assetUrls.vfx.warning,
      sfxUrl: assetUrls.audio.hitBody,
    },
  },
  {
    id: "ember_bolt",
    name: "Ember Bolt",
    description: "Enemy caster nuke that pressures the back line.",
    cooldownMs: 5000,
    resourceCost: 10,
    castTimeMs: 400,
    range: 15,
    targetingMode: "enemy",
    areaShape: "single",
    projectileSpeed: 18,
    effects: [{ type: "damage", power: 26 }],
    aiTags: ["damage", "ranged"],
    asset: {
      vfxUrl: assetUrls.vfx.spellImpactArcane,
      sfxUrl: assetUrls.audio.spellImpact,
    },
  },
  {
    id: "shockwave_slam",
    name: "Shockwave Slam",
    description: "Tank disruptor line attack with knockback pressure.",
    cooldownMs: 9000,
    resourceCost: 18,
    castTimeMs: 550,
    range: 6,
    targetingMode: "skillshot_line",
    areaShape: "line",
    lineLength: 6.5,
    effects: [
      { type: "damage", power: 22, shape: "line" },
      { type: "knockback", power: 2.4, shape: "line" },
    ],
    aiTags: ["damage", "disrupt"],
    asset: {
      vfxUrl: assetUrls.vfx.warning,
      sfxUrl: assetUrls.audio.hitBody,
    },
  },
];

const orders: OrderDefinition[] = [
  {
    id: "follow_me",
    name: "Follow Me",
    description: "Stay mobile around the captain and engage nearby threats.",
    targetMode: "none",
    directive: {
      movement: "follow_leader",
      targetSelection: "nearest_enemy",
      maintainDistance: 4.5,
    },
  },
  {
    id: "hold_position",
    name: "Hold Position",
    description: "Lock current positions and only chase short distances.",
    targetMode: "none",
    directive: {
      movement: "hold",
      targetSelection: "anchor_threat",
      radius: 5.5,
    },
  },
  {
    id: "attack_my_target",
    name: "Attack My Target",
    description: "Collapse on the captain's selected enemy.",
    targetMode: "unit",
    directive: {
      movement: "follow_leader",
      targetSelection: "player_target",
      preferMarkedTarget: true,
    },
  },
  {
    id: "defend_area",
    name: "Defend Area",
    description: "Protect a chosen anchor point and punish intruders.",
    targetMode: "point",
    directive: {
      movement: "anchor",
      targetSelection: "anchor_threat",
      radius: 7.5,
    },
  },
  {
    id: "focus_weakest",
    name: "Focus Weakest",
    description: "Pick off the lowest-health enemy in reach.",
    targetMode: "none",
    directive: {
      movement: "follow_leader",
      targetSelection: "weakest_enemy",
      preferMarkedTarget: true,
    },
  },
  {
    id: "retreat",
    name: "Retreat",
    description: "Break contact and fall back toward the rally point.",
    targetMode: "point",
    directive: {
      movement: "retreat",
      targetSelection: "nearest_enemy",
      maintainDistance: 8,
    },
  },
];

const behaviorProfiles: BehaviorProfileDefinition[] = [
  {
    id: "aggressive",
    name: "Aggressive",
    stance: "aggressive",
    description: "Push damage windows and spend cooldowns early.",
    healThresholdPct: 0.35,
    retreatThresholdPct: 0.18,
    openerSpellId: "arcane_lance",
    rotationSpellIds: ["commanders_mark", "arcane_lance", "volley_burst"],
    focusMarkedTarget: true,
    supportAllies: false,
  },
  {
    id: "defensive",
    name: "Defensive",
    stance: "defensive",
    description: "Protect the line and trade pressure for stability.",
    healThresholdPct: 0.45,
    retreatThresholdPct: 0.26,
    openerSpellId: "guardian_shout",
    rotationSpellIds: ["guardian_shout", "bulwark_pulse", "arcane_lance"],
    focusMarkedTarget: false,
    supportAllies: true,
  },
  {
    id: "support",
    name: "Support",
    stance: "support",
    description: "Prioritize heals, shields, and marked-target follow-up.",
    healThresholdPct: 0.65,
    retreatThresholdPct: 0.24,
    openerSpellId: "field_mend",
    rotationSpellIds: ["field_mend", "bulwark_pulse", "arcane_lance"],
    focusMarkedTarget: true,
    supportAllies: true,
  },
];

const rewards: RewardDefinition[] = [
  {
    id: "steel_discipline",
    name: "Steel Discipline",
    description: "All allied basic attacks hit harder for this run.",
    rarity: "common",
    iconUrl: assetUrls.ui.rewardSword,
    effects: [{ type: "party_bonus", target: "allies", stat: "attackPower", value: 4 }],
  },
  {
    id: "arcane_capacitors",
    name: "Arcane Capacitors",
    description: "The captain gains a deeper resource pool.",
    rarity: "common",
    iconUrl: assetUrls.ui.rewardStaff,
    effects: [{ type: "stat_bonus", target: "leader", stat: "maxResource", value: 18 }],
  },
  {
    id: "battlefield_medicine",
    name: "Battlefield Medicine",
    description: "Improves allied healing and revive strength.",
    rarity: "rare",
    iconUrl: assetUrls.ui.rewardShield,
    effects: [{ type: "party_bonus", target: "allies", stat: "revivePower", value: 10 }],
  },
  {
    id: "companion_drill",
    name: "Companion Drill",
    description: "Companions gain extra move speed and max health.",
    rarity: "common",
    iconUrl: assetUrls.ui.rewardShield,
    effects: [
      { type: "party_bonus", target: "companions", stat: "moveSpeed", value: 0.4 },
      { type: "party_bonus", target: "companions", stat: "maxHp", value: 12 },
    ],
  },
  {
    id: "overcharged_ward",
    name: "Overcharged Ward",
    description: "Bulwark Pulse shields for more and costs less.",
    rarity: "rare",
    iconUrl: assetUrls.ui.rewardStaff,
    effects: [
      { type: "spell_upgrade", target: "leader", spellId: "bulwark_pulse", upgradeKey: "power", value: 12 },
      { type: "spell_upgrade", target: "leader", spellId: "bulwark_pulse", upgradeKey: "resourceCost", value: -4 },
    ],
  },
  {
    id: "honed_edges",
    name: "Honed Edges",
    description: "The captain's saber cadence improves.",
    rarity: "common",
    iconUrl: assetUrls.ui.rewardAxe,
    effects: [{ type: "stat_bonus", target: "leader", stat: "attackPower", value: 5 }],
  },
];

const units: UnitDefinition[] = [
  {
    id: "leader_captain",
    name: "Iron Captain",
    faction: "leader_party",
    controller: "player",
    presentationId: "leader",
    summary: "Third-person leader with a flexible five-spell book and saber basics.",
    group: "all",
    stats: {
      maxHp: 125,
      maxResource: 100,
      moveSpeed: 6.1,
      attackPower: 12,
      spellPower: 18,
      defense: 6,
      revivePower: 12,
    },
    weaponId: "captain_saber",
    spellbookIds: ["arcane_lance", "commanders_mark", "bulwark_pulse", "field_mend", "steam_snare"],
    defaultLoadoutIds: ["commanders_mark", "bulwark_pulse", "steam_snare"],
    behaviorProfileId: "aggressive",
    modelUrl: assetUrls.characters.leader,
    spawnRadius: 0.55,
    reviveable: false,
    xpValue: 0,
  },
  {
    id: "companion_vanguard",
    name: "Vanguard",
    faction: "leader_party",
    controller: "ai",
    presentationId: "companion_melee",
    recruitmentLabel: "Recruit Vanguard",
    summary: "Frontline bruiser that taunts and anchors the formation.",
    group: "frontline",
    stats: {
      maxHp: 112,
      maxResource: 60,
      moveSpeed: 5.4,
      attackPower: 14,
      spellPower: 8,
      defense: 10,
      revivePower: 8,
    },
    weaponId: "vanguard_halberd",
    spellbookIds: ["guardian_shout", "bulwark_pulse"],
    defaultLoadoutIds: ["guardian_shout", "bulwark_pulse"],
    behaviorProfileId: "defensive",
    modelUrl: assetUrls.characters.leader,
    spawnRadius: 0.58,
    reviveable: true,
    xpValue: 0,
  },
  {
    id: "companion_ranger",
    name: "Ranger",
    faction: "leader_party",
    controller: "ai",
    presentationId: "companion_ranged",
    recruitmentLabel: "Recruit Ranger",
    summary: "Backline finisher that capitalizes on marked targets.",
    group: "backline",
    stats: {
      maxHp: 88,
      maxResource: 70,
      moveSpeed: 6.2,
      attackPower: 11,
      spellPower: 10,
      defense: 4,
      revivePower: 7,
    },
    weaponId: "ranger_longbow",
    spellbookIds: ["volley_burst", "commanders_mark"],
    defaultLoadoutIds: ["volley_burst", "commanders_mark"],
    behaviorProfileId: "aggressive",
    modelUrl: assetUrls.characters.companionArcher,
    spawnRadius: 0.5,
    reviveable: true,
    xpValue: 0,
  },
  {
    id: "companion_mender",
    name: "Mender",
    faction: "leader_party",
    controller: "ai",
    presentationId: "companion_support",
    recruitmentLabel: "Recruit Mender",
    summary: "Support specialist focused on healing and shields.",
    group: "support",
    stats: {
      maxHp: 84,
      maxResource: 95,
      moveSpeed: 5.9,
      attackPower: 8,
      spellPower: 15,
      defense: 4,
      revivePower: 15,
    },
    weaponId: "mender_staff",
    spellbookIds: ["field_mend", "bulwark_pulse", "arcane_lance"],
    defaultLoadoutIds: ["field_mend", "bulwark_pulse", "arcane_lance"],
    behaviorProfileId: "support",
    modelUrl: assetUrls.characters.companionArcher,
    spawnRadius: 0.48,
    reviveable: true,
    xpValue: 0,
  },
  {
    id: "enemy_melee_chaser",
    name: "Raider Chaser",
    faction: "enemy",
    controller: "ai",
    presentationId: "enemy_melee",
    summary: "Fast melee enemy that collapses on exposed targets.",
    group: "frontline",
    stats: {
      maxHp: 92,
      maxResource: 45,
      moveSpeed: 6.3,
      attackPower: 13,
      spellPower: 6,
      defense: 4,
      revivePower: 0,
    },
    weaponId: "raider_axe",
    spellbookIds: ["commanders_mark"],
    defaultLoadoutIds: ["commanders_mark"],
    behaviorProfileId: "aggressive",
    modelUrl: assetUrls.characters.enemyAxe,
    spawnRadius: 0.52,
    reviveable: false,
    xpValue: 28,
  },
  {
    id: "enemy_ranged_caster",
    name: "Hexcaster",
    faction: "enemy",
    controller: "ai",
    presentationId: "enemy_ranged",
    summary: "Backline caster that throws ember bolts and control.",
    group: "backline",
    stats: {
      maxHp: 78,
      maxResource: 85,
      moveSpeed: 5.6,
      attackPower: 9,
      spellPower: 14,
      defense: 3,
      revivePower: 0,
    },
    weaponId: "hexcaster_staff",
    spellbookIds: ["ember_bolt", "steam_snare"],
    defaultLoadoutIds: ["ember_bolt", "steam_snare"],
    behaviorProfileId: "aggressive",
    modelUrl: assetUrls.characters.enemyAxe,
    spawnRadius: 0.5,
    reviveable: false,
    xpValue: 32,
  },
  {
    id: "enemy_tank_disruptor",
    name: "Bulwark Disruptor",
    faction: "enemy",
    controller: "ai",
    presentationId: "enemy_tank",
    summary: "Slow tank enemy that taunts and knocks units out of formation.",
    group: "frontline",
    stats: {
      maxHp: 138,
      maxResource: 70,
      moveSpeed: 4.9,
      attackPower: 16,
      spellPower: 10,
      defense: 11,
      revivePower: 0,
    },
    weaponId: "bulwark_maul",
    spellbookIds: ["shockwave_slam", "guardian_shout"],
    defaultLoadoutIds: ["shockwave_slam", "guardian_shout"],
    behaviorProfileId: "defensive",
    modelUrl: assetUrls.characters.enemyAxe,
    spawnRadius: 0.62,
    reviveable: false,
    xpValue: 42,
  },
];

const loadouts: SpellLoadoutDefinition[] = [
  {
    id: "leader_spellbook",
    ownerId: "leader_spellbook",
    spellIds: ["arcane_lance", "commanders_mark", "bulwark_pulse", "field_mend", "steam_snare"],
    slotCount: 3,
  },
  {
    id: "companion_vanguard_default",
    ownerId: "companion_vanguard",
    spellIds: ["guardian_shout", "bulwark_pulse"],
    slotCount: 2,
  },
  {
    id: "companion_ranger_default",
    ownerId: "companion_ranger",
    spellIds: ["volley_burst", "commanders_mark"],
    slotCount: 2,
  },
  {
    id: "companion_mender_default",
    ownerId: "companion_mender",
    spellIds: ["field_mend", "bulwark_pulse", "arcane_lance"],
    slotCount: 3,
  },
];

export const prototypeCatalog: PrototypeCatalog = {
  factions: byId(factions),
  weapons: byId(weapons),
  spells: byId(spells),
  statuses: byId(statuses),
  orders: byId(orders),
  rewards: byId(rewards),
  loadouts: byId(loadouts),
  behaviorProfiles: byId(behaviorProfiles),
  units: byId(units),
};

export const catalogSummary = {
  factionCount: factions.length,
  weaponCount: weapons.length,
  spellCount: spells.length,
  statusCount: statuses.length,
  orderCount: orders.length,
  rewardCount: rewards.length,
  behaviorProfileCount: behaviorProfiles.length,
  unitCount: units.length,
  leaderSpellbookSlots: prototypeCatalog.loadouts.leader_spellbook.slotCount,
} as const;
